### ISSUE TITLE
player.soldier:GetWeaponNameByIndex(i) crash

### ISSUE THREAD

**Issue by 3ti65** [VeniceUnleashed/VeniceUnleashed#261]
When using a index that is out of range, this function crashes the server. (when executed on server)

should not crash but instead print an error.

**Comment by OrfeasZ** [comment]
Please provide a mod and loadout configuration that replicates this issue.

**Comment by kiwidoggie** [comment]
Should be fixed in build 12321 (pending push).

**Comment by 3ti65** [comment]
Tested, crash no longer appears.

**Comment by 3ti65** [comment]
Edit:

Still appears to crash under certain circumstances. Trying to narrow it down, but here's the crashdump:

[GetWeaponNameByIndexCrashDump.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/1595287/GetWeaponNameByIndexCrashDump.zip)

Reopen for now

**Comment by 3ti65** [comment]
https://i.imgur.com/jccbKTl.png

seems to crash (sometimes) after the last existing weaponslot

**Comment by 3ti65** [comment]
[GetWeaponNameByIndexCrashTestMod.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/1595296/GetWeaponNameByIndexCrashTestMod.zip)

Testmod attached.
Steps to reproduce:
- spawn with writing in chat 'spawn'
- after landing write in chat 'debug'

-> server crashes. check server debug console to see the same as the pic provided in last comment.
