### ISSUE TITLE
[Crash] Custom rcon commands silently crash server when called from rcon.

### ISSUE THREAD

**Issue by FoolHen** [VeniceUnleashed/VeniceUnleashed#556]
[Test.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/5721125/Test.zip)

Run ``rcontest`` command from procon.

**Comment by FlashHit** [comment]
I believe you have to return sth.
like `return {'OK'}`

**Comment by kiwidoggie** [comment]
@FlashHit is correct, you will need to change the mod to be

```
commandHandle = RCON:RegisterCommand('rcontest', RemoteCommandFlag.RequiresLogin, function() print('nice')
    return { "OK" }
end)
```

but the crash has been fixed by improved error handling. Now the mod that you originally posted will return "InternalError" if you forget to return a status instead of crashing. Will close when fix is pushed

**Comment by kiwidoggie** [comment]
This was fixed awhile ago in 17394. Forgot to update + close.

**Comment by FoolHen** [comment]
It still crashes, and doesn't print any error before crashing @kiwidoggie 
I'll try returning OK status, didn't know I need that
