### ISSUE TITLE
[Bug] Using either vu.com or -headless does not prevent the error window from popping up

### ISSUE THREAD

**Issue by lywit** [VeniceUnleashed/VeniceUnleashed#723]
I a previous issue it was recommended to me to use -headless or vu.com to stop the error popup from showing up. It seems that doing this does **not** prevent the error popup. It still shows up and thus prevents servers from restarting automatically in a batch loop.

Here is my previous issue on the topic:
https://github.com/EmulatorNexus/VeniceUnleashed/issues/621

**Comment by kiwidoggie** [comment]
I cannot repro this, using `-headless` does not produce a prompt on crash. Do you have an example mod that causes this?

**Comment by paulhobbel** [comment]
I can indeed confirm this happens on headless mode. I run my dedi in headless mode all the time and it always shows the error dialog.

**Comment by FlashHit** [comment]
Just tested. Can confirm it as well.

Here a mod that causes a prompt on crash: [ReproClassPrint.zip](https://github.com/EmulatorNexus/VeniceUnleashed/files/7656411/ReproClassPrint.zip)

**Comment by OrfeasZ** [comment]
Fixed in `18244`.

**Comment by FlashHit** [comment]
@OrfeasZ I still get the error window even I run the latest build with `-headless`

**Comment by FlashHit** [comment]
can someone else verify that this issue is not fixed?

**Comment by FlashHit** [comment]
seems to work now.
